version: "2"
services:
  otel-collector:
    build:
      dockerfile: Dockerfile
      context: ../../
    #command: ["--config=local/config.yaml", "${OTELCOL_ARGS}"]
    # volumes:
    #    - c:/Lib/Docker-Go:/go
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55670:55679" # zpages extension
  pet-clinic:
    build:
      dockerfile: Dockerfile
      context: ../../examples/java
    ports:
      - "19080:8080"